import {serviceModel, staffModel} from "../../../DB/model/relations.js"
import {AppError} from "../../utils/AppError.js";

export const assignServicesToStaff = async (req, res, next) => {
    const { staffId } = req.params; // Staff ID from the request parameters
    const { serviceIds } = req.body; // Array of service IDs from the request body

    if (!Array.isArray(serviceIds) || serviceIds.length === 0) {
        return next(new AppError("Invalid service IDs provided. Please pass a non-empty array.", 400));
    }

    const staff = await staffModel.findByPk(staffId);
    if (!staff) {
        return next(new AppError("Staff member not found", 404));
    }

    const validServices = await serviceModel.findAll({
        where: { id: serviceIds },
    });
    if (validServices.length !== serviceIds.length) {
        return next(new AppError("Some service IDs are invalid or do not exist", 400));
    }

    await staff.addServices(serviceIds); // 'addServices' is generated by Sequelize due to the belongsToMany relationship

    return res.status(200).json({
        message: "Services successfully assigned to the staff member",
        assignedServices: serviceIds,
    });
};